name: Deploy TheGraph Subgraphs

# This workflow is triggered when changes are pushed to the subgraphs folders into the main branch.
on:
  push:
    branches:
      - 'main'
    paths:
      - 'subgraphs/generated/live/sepolia/eip721/**'
      - 'subgraphs/generated/live/sepolia/eip1155/**'

jobs:    
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          eip721:
            - 'subgraphs/generated/live/sepolia/eip721/**'
          eip1155:
            - 'subgraphs/generated/live/sepolia/eip1155/**'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.1'
    

    - name: Install Graph CLI
      run: npm install -g @graphprotocol/graph-cli@0.49.0
    
    - name: Install utilities
      run: pip install shyaml 
    
    - name: Install dependencies
      run: |
        cd ${{ github.workspace }}/subgraphs/
        npm install
    
    - name: Authenticate with GitHub Package Registry
      run: graph auth --studio ${{ secrets.THE_GRAPH_STUDIO_TOKEN }}

    - name: Build and deploy eip1155 Subgraph
      if:  steps.filter.outputs.eip1155 == 'true'
      run: |
        cd ${{ github.workspace }}/subgraphs/generated/live/sepolia/eip1155
        graph codegen
        graph build
        version=`cat ${{ github.workspace }}/subgraphs/generated/live/sepolia/eip1155/subgraph.yaml | shyaml get-value specVersion`
        graph deploy --studio otomee-eip1155-sepolia --version-label $version

    - name: Build and deploy eip721 Subgraph
      if: ${{ steps.filter.outputs.eip721 == 'true' }}
      run: |
        cd ${{ github.workspace }}/subgraphs/generated/live/sepolia/eip721
        graph codegen
        graph build
        version=`cat ${{ github.workspace }}/subgraphs/generated/live/sepolia/eip721/subgraph.yaml | shyaml get-value specVersion`
        graph deploy --studio otomee-eip721-sepolia --version-label $version