name: Deploy TheGraph Subgraphs

# This workflow is triggered when changes are pushed to the subgraphs folders.
on:
  push:
    paths:
      - 'subgraphs/generated/live/goerli/eip721/**'
      - 'subgraphs/generated/live/goerli/eip1155/**'

jobs:    
  deploy-eip721:
    
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.modified, 'subgraphs/generated/live/goerli/eip721/') }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.1'
    
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.lock') }}
        restore-keys: ${{ runner.os }}-node-modules-

    - name: Install Graph CLI
      run: npm install -g @graphprotocol/graph-cli
    
    - name: Build eip721 Subgraph
      run: |
        cd subgraphs/generated/live/goerli/eip721
        graph codegen
        graph build
    
    - name: Authenticate with GitHub Package Registry
      run: graph auth --studio ${{ secrets.THE_GRAPH_STUDIO_TOKEN }}
    
    - name: Deploy The Subgraph
      run: |
        graph deploy --studio otomee-eip721-goerli

  deploy-eip1155:
    runs-on: ubuntu-latest
    
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          eip721:
            - 'subgraphs/generated/live/goerli/eip721/**'
          eip1155:
            - 'subgraphs/generated/live/goerli/eip1155/**'
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.1'
    
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.lock') }}
        restore-keys: ${{ runner.os }}-node-modules-

    - name: Install Graph CLI
      run: npm install -g @graphprotocol/graph-cli
    
    - name: Authenticate with GitHub Package Registry
      run: graph auth --studio ${{ secrets.THE_GRAPH_STUDIO_TOKEN }}

    - name: Build and deploy eip1155 Subgraph
      if: steps.filter.outputs.eip1155 == 'true'
      run: |
        cd ${{ github.workspace }}/subgraphs/generated/live/goerli/eip1155
        graph codegen
        graph build
        graph deploy --studio otomee-eip1155-goerli

    - name: Build and deploy eip721 Subgraph
      if: steps.filter.outputs.eip721 == 'true'
      run: |
        cd ${{ github.workspace }}/subgraphs/generated/live/goerli/eip721
        graph codegen
        graph build
        graph deploy --studio otomee-eip721-goerli