name: Test TheGraph Subgraphs

# This workflow is triggered when changes are pushed to the subgraphs folders.
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'subgraphs/generated/live/goerli/eip721/**'
      - 'subgraphs/generated/live/goerli/eip1155/**'

jobs:    
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          eip721:
            - 'subgraphs/generated/live/goerli/eip721/**'
          eip1155:
            - 'subgraphs/generated/live/goerli/eip1155/**'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.1'
    

    - name: Install Graph CLI
      run: npm install -g @graphprotocol/graph-cli@0.49.0
    
    - name: Install dependencies
      run: |
        cd ${{ github.workspace }}/subgraphs/
        npm install

    - name: Build eip1155 Subgraph
      if:  steps.filter.outputs.eip1155 == 'true'
      run: |
        cd ${{ github.workspace }}/subgraphs/generated/live/goerli/eip1155
        graph codegen
        graph build

    - name: Build eip721 Subgraph
      if: ${{ steps.filter.outputs.eip721 == 'true' }}
      run: |
        cd ${{ github.workspace }}/subgraphs/generated/live/goerli/eip721
        graph codegen
        graph build
